// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuzlmfntigskoxhwbiav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1emxtZm50aWdza294aHdiaWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDI2NTIsImV4cCI6MjA3NDcxODY1Mn0.DEMV45Eo4UVfcCTKM3I6XgAmbL8owzJyKnNXZn1lvDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});