name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Supabase CLI
        run: |
          wget -qO- https://github.com/supabase/cli/releases/latest/download/install.sh | bash -s -- -b ./bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Check Supabase CLI version
        run: supabase --version

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Deploy analyze-intake function
        run: supabase functions deploy analyze-intake

      - name: Deploy generate-matches function
        run: supabase functions deploy generate-matches
      

   
