# This workflow deploys Supabase Edge Functions on pushes to the main branch.

name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_REF }}
    
    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Supabase CLI
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Step 4: Deploy Edge Functions directly (no link needed with env vars)
      - name: Deploy analyze-intake function
        run: supabase functions deploy analyze-intake --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Deploy generate-matches function
        run: supabase functions deploy generate-matches --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
