name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download Supabase CLI
        run: |
          wget -qO supabase.tar.gz https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-amd64.tar.gz
          tar -xzf supabase.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

      - name: Check Supabase CLI version
        run: supabase --version

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Deploy analyze-intake function
        run: supabase functions deploy analyze-intake

      - name: Deploy generate-matches function
        run: supabase functions deploy generate-matches
